name: code-style

on:
- push
- pull_request

jobs:
  phpstan:
    name: PHPCS
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "7.2"
        ini-values: memory_limit=-1
        tools: composer:v2, phpcs
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.composer/cache
          vendor
        key: vendor

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Run PHPCS
      run: phpcs
